package tsgen

import (
	"regexp"
	"strings"

	"github.com/ceymard/rel/pg"
	tsembed "github.com/ceymard/rel/typescript"
)

// localImportLine matches one `import ... from "./..."` statement — single-
// line or a multi-line named-import block alike (querier.ts's own `import
// type { ... } from "./shapes"` spans several lines) — querier.ts/query.ts/
// shapes.ts's own local imports (specs/typescript.md ## database.ts : "each
// with its own local `import ... from "./..."` line ... stripped first"),
// needed for the typescript/ directory to type-check as separate files
// today but meaningless once concatenated into one file.
var localImportLine = regexp.MustCompile(`(?ms)^import\b.*?from\s+"\./[^"]*"\n`)

func stripLocalImports(src string) string {
	return localImportLine.ReplaceAllString(src, "")
}

// GenerateDatabaseTS is specs/typescript.md ## database.ts's full output : a
// single, self-sufficient .ts file with no imports — querier.ts + the
// generated schema (GenerateSchema) + query.ts + shapes.ts, in that fixed
// order (## File layout's three sections).
func GenerateDatabaseTS(db *pg.DbInfos, opts Options) string {
	var b strings.Builder
	b.WriteString("// Generated by rel (specs/typescript.md ## database.ts). Do not edit by hand.\n\n")
	b.WriteString(stripLocalImports(tsembed.QuerierTS))
	b.WriteString("\n")
	b.WriteString(GenerateSchema(db, opts))
	b.WriteString(stripLocalImports(tsembed.QueryTS))
	b.WriteString("\n")
	b.WriteString(stripLocalImports(tsembed.ShapesTS))
	return b.String()
}
