package tsgen

import (
	"regexp"
	"strings"

	"github.com/rel-server/rel/pg"
	tsembed "github.com/rel-server/rel/typescript"
	"github.com/rel-server/rel/wellknown"
)

// localImportLine matches one `import ... from "./..."` statement — single-
// line or a multi-line named-import block alike (querier.ts's own `import
// type { ... } from "./shapes"` spans several lines) — querier.ts/query.ts/
// shapes.ts's own local imports (specs/typescript.md ## database.ts : "each
// with its own local `import ... from "./..."` line ... stripped first"),
// needed for the typescript/ directory to type-check as separate files
// today but meaningless once concatenated into one file.
var localImportLine = regexp.MustCompile(`(?ms)^import\b.*?from\s+"\./[^"]*"\n`)

func stripLocalImports(src string) string {
	return localImportLine.ReplaceAllString(src, "")
}

// GenerateDatabaseTS produces database.ts's full output : a single, self-sufficient .ts file with no imports —
// pg_values.ts (specs/typescript-wire-types.md's branded types/Range/Temporal-backed accessors, first so the
// generated schema below can reference its names) + querier.ts + the generated schema (GenerateSchema) +
// query.ts + shapes.ts, in that fixed order.
func GenerateDatabaseTS(db *pg.DbInfos, opts Options, wkReg *wellknown.Registry) string {
	var b strings.Builder
	b.WriteString("// Generated by rel (specs/typescript-wire-types.md). Do not edit by hand.\n\n")
	b.WriteString(stripLocalImports(tsembed.PgValuesTS))
	b.WriteString("\n")
	b.WriteString(stripLocalImports(tsembed.QuerierTS))
	b.WriteString("\n")
	b.WriteString(GenerateSchema(db, opts, wkReg))
	b.WriteString(stripLocalImports(tsembed.QueryTS))
	b.WriteString("\n")
	b.WriteString(stripLocalImports(tsembed.ShapesTS))
	return b.String()
}
