package main

import (
	"fmt"
	"io"
	"net/http"
	"regexp"
	"sort"
	"strings"

	"github.com/go-chi/chi"
	"sales-way.com/server/pg"
	"sales-way.com/server/sw"
)

var re_snal = regexp.MustCompile(`(^|_)([a-zA-Z$0-9])`)

type Col interface {
	TypeName() string
}

func decoderExp(col Col) string {
	var s = col.TypeName()

	if strings.HasPrefix(s, "json") {
		return "s.as_is"
	}

	if s == "text" || s == "varchar" {
		return "s.str"
	}

	if s == "bool" {
		return "s.str"
	}

	if strings.HasPrefix(s, "int") ||
		strings.HasPrefix(s, "float") ||
		s == "bigint" ||
		s == "numeric" {
		return "s.num"
	}

	if strings.HasPrefix(s, "timestamp") || s == "date" {
		return "s.date"
	}

	return fmt.Sprintf("p.Decoder(\"%s\")", s)
}

func JavascriptName(s string) string {

	if s == "text" {
		return "string"
	}

	if s == "bool" {
		return "boolean"
	}

	if strings.HasPrefix(s, "int") ||
		strings.HasPrefix(s, "float") ||
		s == "bigint" ||
		s == "numeric" {
		return "number"
	}

	if strings.HasPrefix(s, "timestamp") || s == "date" {
		return "Date"
	}

	if strings.HasPrefix(s, "json") {
		return "unknown"
	}

	return `p.PgType<"` + s + `">`
}

func ColumnJavascriptType(c Col) string {
	return JavascriptName(c.TypeName())
}

func SnakeCase(s string) string {
	return re_snal.ReplaceAllStringFunc(s, func(s string) string {
		if s[0] == '_' {
			return strings.ToUpper(s[1:])
		}
		return strings.ToUpper(s)
	})
}

func Preamble(srv *sw.SwServer, w io.Writer) {
	fmt.Fprintf(w, `/**
 * WARNING
 * THIS FILE WAS GENERATED BY goserver
 * ONLY EDIT CODE BETWEEN !impl and !end impl comments
 */

import { s } from "@salesway/pgts";
import * as p from "@salesway/pgts";

/** !impl FILE_HEADER **//** !end impl FILE_HEADER **/

`)
	for _, nsmp := range srv.Schemas {
		fmt.Fprintf(w, "export function %s() {}\n\n", nsmp)
	}

}

func writeFunctions(srv *sw.SwServer, w io.Writer) {
	for _, f := range srv.Functions {
		fmt.Fprintf(w, "%s.%s = function %s() {}\n\n", f.Schema, f.Name, f.Name)
	}
}

type PgColumn struct {
	*pg.DBColumn
}

func (p *PgColumn) TypeName() string {
	return p.Type
}

type PgComputedColumn struct {
	*pg.ComputedColumn
}

func (p *PgComputedColumn) TypeName() string {
	return p.ComputedColumn.Type
}

func writeClasses(srv *sw.SwServer, w io.Writer) {

	for _, table := range srv.Tables {
		var class_name = SnakeCase(table.Name)
		var full_name = table.Schema + "." + class_name
		fmt.Fprintf(w, "%s = class %s extends p.Model {\n", full_name, class_name)
		for _, column := range table.ColumnsInOrder {
			var c = &PgColumn{column}
			fmt.Fprintf(w, "  @(%s)", decoderExp(c))
			fmt.Fprintf(w, " %s: %s;\n", column.Name, ColumnJavascriptType(c))
		}

		if len(table.ComputedColumns) > 0 {
			fmt.Fprintf(w, "\n  // Computed Columns\n")
		}
		for _, column := range table.ComputedColumns {
			var c = &PgComputedColumn{column}
			fmt.Fprintf(w, "  @(%s.RO)", decoderExp(c))
			fmt.Fprintf(w, " %s: %s;\n", column.Name, ColumnJavascriptType(c))
		}

		fmt.Fprintf(w, "\n  /** !impl %s **//** !end impl %s **/\n}\n\n", full_name, full_name)
	}
}

// Remplacement de pgts

func setupPgTypescript(srv *sw.SwServer) error {

	if ENABLE_TS_SCHEMAS != "" {
		srv.Router.Get("/scripts/{schema}.ts", func(w http.ResponseWriter, r *http.Request) {
			schema := chi.URLParam(r, "schema")

			if schema == "model" {
				w.Write([]byte(modelTs))
				return
			}

			var wr = &pg.TypescriptWriter{Writer: w, CurrentSchema: schema}

			var tables = make([]*pg.DBTable, 0)

			for _, table := range srv.Tables {
				if table.Schema == schema {
					tables = append(tables, table)
				}
			}

			var functions = make([]*pg.Function, 0)
			for _, function := range srv.Functions {
				if function.Schema == schema {
					functions = append(functions, function)
				}
			}

			sort.Slice(tables, func(i, j int) bool {
				return tables[i].Name < tables[j].Name
			})
			sort.Slice(functions, func(i, j int) bool {
				return functions[i].Name < functions[j].Name
			})

			pg.OutputTypescriptSchema(wr, schema, tables, functions)
		})
	}

	return nil
}
