package query

import (
	"iter"
)

// For a given selection, return the list of columns that are selected, and the path to the json column that contains the value in the json object that would be generated by this selection.
func (sel *AstSelection) SelectedFields() iter.Seq2[any, string] {

	return func(yield func(any, string) bool) {
		var fn func(IAstField, string) bool

		fn = func(field IAstField, prefix string) bool {

			if ast_field, ok := field.(*AstSimpleField); ok {

				colname, ok := ast_field.Expression.(*Identifier)
				if !ok {
					// Not an identifier, but we'll still keep looking
					return true
				}

				col, ok := sel.ResolvedTable.Columns[colname.Identifier]
				if !ok {
					// Not a column in this table, but we'll still keep looking
					return true
				}

				return yield(col, prefix+"->'"+colname.Identifier+"'")
			}

			if ast_group, ok := field.(*AstFieldGroup); ok {
				for _, v := range ast_group.Fields {
					if !fn(v, prefix+"->'"+ast_group.Name+"'") {
						return false
					}
				}
			}

			if star, ok := field.(*AstStarSelector); ok {
				pref := ""

				if star.Name != "" {
					pref = "->'" + star.Name + "'"
				}

				if prefix != "" {
					pref = prefix + pref
				}

				for _, v := range sel.ResolvedTable.ColumnsInOrder {
					if star.Exclusions.Has(v.Name) {
						continue
					}

					if !yield(v, pref+"->'"+v.Name+"'") {
						return false
					}
				}
			}

			if rel, ok := field.(*AstRelationshipField); ok {
				if !yield(rel, prefix+"->'"+rel.Alias+"'") {
					return false
				}
			}

			return true
		}

		for _, v := range sel.Fields {
			if !fn(v, "") {
				return
			}
		}
	}
}
